# -*- coding: utf-8 -*-
"""najeon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STUwu4w8YAM4-zoZILaqWPjyzKFvPzLE
"""



import math
import random
from IPython.display import SVG, display

# ==========================================
# (a) COLOR PALETTE FUNCTION
# ==========================================
def get_najeon_palette(num_colors=6):
    """
    Generates a random palette of shimmering mother-of-pearl (Najeon) hues:
    soft iridescence (pinks, teals, lavenders, mints, and pearl creams).
    Returns colors as hex codes.
    """
    palette = []
    for _ in range(num_colors):
        hue_choice = random.choice(["teal_green", "pink_violet", "pearl_cream"])

        if hue_choice == "teal_green":
            r, g, b = random.randint(80, 160), random.randint(200, 255), random.randint(200, 245)
        elif hue_choice == "pink_violet":
            r, g, b = random.randint(210, 255), random.randint(140, 200), random.randint(210, 255)
        else:  # pearl_cream
            r, g, b = random.randint(230, 250), random.randint(235, 255), random.randint(220, 245)

        palette.append(f"#{r:02x}{g:02x}{b:02x}") # Return hex
    return palette

# Utility functions for color manipulation
def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip('#')
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(rgb_tuple):
    return f"#{rgb_tuple[0]:02x}{rgb_tuple[1]:02x}{rgb_tuple[2]:02x}"

def adjust_brightness(hex_color, factor): # factor > 1 to lighten, < 1 to darken
    rgb = hex_to_rgb(hex_color)
    new_rgb = tuple(min(255, max(0, int(c * factor))) for c in rgb)
    return rgb_to_hex(new_rgb)


# ==========================================
# (b) BLOB GENERATOR
# ==========================================
def generate_blob_path(cx, cy, base_radius, num_points=12, wobble=0.25):
    """
    Generates a smooth, organic 'blob' SVG path string using
    cubic Bézier curves with parameterized radius and wobble.
    """
    points = []
    angle_step = (2 * math.pi) / num_points

    # Pre-calculate a random orientation for the shell shape
    shape_offset_angle = random.uniform(0, 2 * math.pi)

    # 1. Generate polar vertices with randomized radial offsets
    for i in range(num_points):
        angle = i * angle_step

        # Introduce angular-dependent deformation for a shell-like shape
        # Makes the blob wider on one side and narrower on the other
        shape_modulation_strength = 0.4 # How much to deform from a perfect circle
        modified_base_radius = base_radius * (1 + shape_modulation_strength * math.sin(angle + shape_offset_angle))

        # Apply wobble parameter to perturb the modified radius
        r_offset = random.uniform(-wobble, wobble) * modified_base_radius
        r = max(10, modified_base_radius + r_offset)

        x = cx + r * math.cos(angle)
        y = cy + r * math.sin(angle)
        points.append((x, y))

    # 2. Smooth points into a closed SVG Path using smooth Bézier tangents
    path_commands = []
    n = len(points)

    for i in range(n):
        p0 = points[(i - 1) % n]
        p1 = points[i]
        p2 = points[(i + 1) % n]
        p3 = points[(i + 2) % n]

        # Calculate smooth control points (Catmull-Rom to Cubic Bézier conversion)
        cp1_x = p1[0] + (p2[0] - p0[0]) / 6.0
        cp1_y = p1[1] + (p2[1] - p0[1]) / 6.0

        cp2_x = p2[0] - (p3[0] - p1[0]) / 6.0
        cp2_y = p2[1] - (p3[1] - p1[1]) / 6.0

        if i == 0:
            path_commands.append(f"M {p1[0]:.2f} {p1[1]:.2f}")

        path_commands.append(
            f"C {cp1_x:.2f} {cp1_y:.2f}, {cp2_x:.2f} {cp2_y:.2f}, {p2[0]:.2f} {p2[1]:.2f}"
        )

    path_commands.append("Z")
    return " ".join(path_commands)


# ========================================== # (c) MAIN DRAW FUNCTION WITH PARAMETERS # ==========================================
def draw(width=800, height=1000, num_blobs=8, min_radius=40, max_radius=100, wobble=0.35, seed=None):
    """
    Main renderer that outputs a complete Najeon-themed SVG poster string.
    """
    if seed is not None:
        random.seed(seed)

    # Define common SVG filters
    svg_defs = [
        '<defs>',
        '  <filter id="najeon-glow" x="-20%" y="-20%" width="140%" height="140%">',
        '    <feGaussianBlur stdDeviation="3" result="blur" />',
        '    <feComposite in="SourceGraphic" in2="blur" operator="over" />',
        '  </filter>',
        '  <filter id="blur-effect">', # Simple blur for shadows
        '    <feGaussianBlur in="SourceGraphic" stdDeviation="3" />',
        '  </filter>',
    ]

    gradient_defs = [] # To store dynamic gradients for each blob
    blob_elements_with_shadows = []

    palette = get_najeon_palette(num_colors=num_blobs) # Now returns hex colors

    center_x, center_y = width / 2, height / 2

    for i in range(num_blobs):
        # Concentric layering from largest (background) to smallest (foreground)
        t = i / max(1, num_blobs - 1)
        base_radius = max_radius - t * (max_radius - min_radius)

        # Distribute blobs across a wider area to avoid stacking
        offset_range_x = width * 0.4  # e.g., 40% of width
        offset_range_y = height * 0.4 # e.g., 40% of height

        cx = center_x + random.uniform(-offset_range_x, offset_range_x)
        cy = center_y + random.uniform(-offset_range_y, offset_range_y)

        # --- Shadow Layer (before main blob to appear beneath) ---
        shadow_path_d = generate_blob_path(
            cx=cx + 6,  # Offset for shadow
            cy=cy + 6,  # Offset for shadow
            base_radius=base_radius,
            num_points=random.randint(8, 14),
            wobble=wobble
        )
        blob_elements_with_shadows.append(
            f'  <path d="{shadow_path_d}" fill="#000000" fill-opacity="0.4" filter="url(#blur-effect)" />'
        )

        # --- Gradient for main blob ---
        base_hex_color = palette[i]
        light_hex_color = adjust_brightness(base_hex_color, 1.3) # Lighter
        dark_hex_color = adjust_brightness(base_hex_color, 0.7)  # Darker

        gradient_id = f"blob_grad_{i}"
        gradient_defs.append(
            f'  <linearGradient id="{gradient_id}" x1="0%" y1="0%" x2="100%" y2="100%">\n'
            f'    <stop offset="0%" stop-color="{light_hex_color}" stop-opacity="0.9" />\n'
            f'    <stop offset="50%" stop-color="{base_hex_color}" stop-opacity="0.75" />\n'
            f'    <stop offset="100%" stop-color="{dark_hex_color}" stop-opacity="0.9" />\n'
            f'  </linearGradient>'
        )

        # --- Main Blob Layer ---
        blob_path_d = generate_blob_path(
            cx=cx,
            cy=cy,
            base_radius=base_radius,
            num_points=random.randint(8, 14),
            wobble=wobble
        )

        stroke_color = "rgba(255, 255, 255, 0.4)"
        blob_elements_with_shadows.append(
            f'  <path d="{blob_path_d}" fill="url(#{gradient_id})" stroke="{stroke_color}" stroke-width="0.8" />'
        )

    # Combine all SVG elements
    svg_defs.extend(gradient_defs)
    svg_defs.append('</defs>')

    svg_elements = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">',
        f'<rect width="{width}" height="{height}" fill="#0C0A0A" />',
    ]
    svg_elements.extend(svg_defs) # Add all defs here
    svg_elements.append('<g filter="url(#najeon-glow)">') # Apply overall glow to all blobs and shadows
    svg_elements.extend(blob_elements_with_shadows) # Add all blobs and shadows
    svg_elements.append('</g>')
    svg_elements.append('</svg>')

    svg_code = "\n".join(svg_elements)
    return svg_code

# --- Run & Render directly in Google Colab ---
svg_output = draw(num_blobs=8, wobble=0.30, seed=42)
display(SVG(svg_output))

"""### Make the Blob Generator Interactive

Now, let's add interactive controls to modify the generated SVG in real-time. We'll use `ipywidgets` to create sliders for various parameters of the `draw` function, allowing you to experiment with different blob configurations.
"""

import ipywidgets as widgets
from ipywidgets import interact, IntSlider, FloatSlider
from IPython.display import display, SVG

# Define an interactive function that wraps the draw function
def interactive_draw(num_blobs, min_radius, max_radius, wobble, seed):
    """
    Interactive wrapper for the draw function to generate and display SVG.
    """
    svg_output = draw(
        width=800,
        height=1000,
        num_blobs=num_blobs,
        min_radius=min_radius,
        max_radius=max_radius,
        wobble=wobble,
        seed=seed
    )
    display(SVG(svg_output))

# Create the interactive controls by passing the function and widget definitions to interact
interact(
    interactive_draw,
    num_blobs=widgets.IntSlider(min=1, max=20, step=1, value=8, description='Number of Blobs'),
    min_radius=widgets.IntSlider(min=10, max=150, step=5, value=40, description='Min Radius'),
    max_radius=widgets.IntSlider(min=50, max=300, step=10, value=100, description='Max Radius'),
    wobble=widgets.FloatSlider(min=0.0, max=1.0, step=0.05, value=0.30, description='Wobble'),
    seed=widgets.IntSlider(min=0, max=1000, step=1, value=42, description='Random Seed')
);

file_name = 'najeon_poster.svg'
with open(file_name, 'w') as f:
    f.write(svg_output)
print(f'SVG poster saved as {file_name}')